#!/usr/bin/env bash
set -uo pipefail
ART=9719216316
OUTER=acb43cf0ec79437408c782193ece354eb790d9ae2159eaeb42546546ea20c3fc
SRC=755485865a7cf9c485d754f22b82a41ee151824b
SRC_SHA=78ca517ac7b96ee3737d6ae5b277fc4d06e7393c460f4c9585eb35b2541d84cf
E="$RUNNER_TEMP/r7-evidence"; W="$RUNNER_TEMP/r7-work"; R="$RUNNER_TEMP/r7-result"; H="$RUNNER_TEMP/r7-harness.py"
mkdir -p "$E/processes" "$W" "$R"; : > "$E/execution-ledger.tsv"; : > "$E/not-run.tsv"
STATUS=ORCHESTRATION_RED; REASON=uninitialized; RUNTIME=0; ACCEPTED_GREEN=0; ACCEPTED_STOP=0; HAVE_BASE=0
inv(){ local root=$1 out=$2; (cd "$root" && find . -type f -printf '%P\t%m\t%s\t' | LC_ALL=C sort | while IFS=$'\t' read -r p m s; do printf '%s\t%s\t%s\t' "$p" "$m" "$s"; sha256sum "$p"|cut -d' ' -f1; done)>"$out"; }
owner(){ case "$1" in FieldTransportAtlas|SurfaceCellAuthorityKernel) echo directional_surface_cell_authority_kernel_tests;; FlowRepStrandsPhase15|PatchDescriptorMilestoneE|PureQuadCompletionPhase18|SurfaceArrangementPhase16|SurfaceCellSourceSupportAndChartAuthority|SurfaceComplexSimplificationPhase17) echo directional_surface_cell_completion_tests;; SourceAuthoritativeMeshValidatorPhase22|SurfaceMeshOptimizerPhase19|SurfaceMeshOptimizerPhase22|SurfaceOptimizationRailAuthorityMigration) echo directional_surface_cell_validation_tests;; *) echo directional_surface_cell_producer_tests;; esac; }
run1(){ local phase=$1 id=$2 bin=$3 ord=${4:-NA}; local p="$E/processes/${phase}-$(printf '%s' "$ord-$id"|sha256sum|cut -c1-16)"; python3 "$H" "$W/package/bin/$bin" "$id" "$p" > "$p.harness.log" 2>&1 || return 90; local rc cnt; rc=$(jq -r .returncode "$p.json"); cnt=$(jq -r .run_count "$p.json"); printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$phase" "$ord" "$id" "$bin" "$rc" "$cnt" >> "$E/execution-ledger.tsv"; [[ "$cnt" == 1 ]] || return 91; [[ "$rc" =~ ^-?[0-9]+$ ]] || return 92; RUN_RC=$rc; }
post(){ local tag=$1 ok=1; if [[ $HAVE_BASE == 1 ]]; then inv "$W/package" "$E/package-after.tsv" || ok=0; inv "$GITHUB_WORKSPACE" "$E/source-after.tsv" || ok=0; cmp -s "$E/package-before.tsv" "$E/package-after.tsv" || ok=0; cmp -s "$E/source-before.tsv" "$E/source-after.tsv" || ok=0; (cd "$W/package" && sha256sum -c SHA256SUMS > "$E/postflight-sha256sums.txt" 2>&1) || ok=0; fi; [[ -f "$W/package.zip" ]] && [[ $(sha256sum "$W/package.zip"|cut -d' ' -f1) == "$OUTER" ]] || ok=0; printf 'phase=%s\npostflight_integrity=%s\nbenchmarkExecution=false\nconfigure=false\ncompile=false\nrelink=false\nrepair=false\ngeneratedDiscovery=false\nsourceMutation=false\ntestMutation=false\nfixtureMutation=false\nselectorMutation=false\npackageMutation=false\n' "$tag" "$([[ $ok == 1 ]]&&echo pass||echo fail)" > "$E/postflight.txt"; [[ $ok == 1 ]]; }
finish(){ local ex=$1; post "$([[ $RUNTIME == 1 ]]&&echo R7-6||echo R7-0-integrity)" || { STATUS=ORCHESTRATION_RED; REASON=postflight_integrity_failure; ex=2; }; printf '357\tNOT-RUN\tfrozen-R7-non-action\n358\tNOT-RUN\tfrozen-R7-non-action\ncumulative-gate\tNOT-RUN\tfrozen-R7-non-action\nbenchmarks\tNOT-RUN\tfrozen-R7-non-action\n' >> "$E/not-run.tsv"; [[ $RUNTIME == 1 ]] || printf 'R7-2..R7-5\tNOT-RUN\tpreflight-stop\nR7-1\tNOT-RUN\tpreflight-stop\n' >> "$E/not-run.tsv"; [[ $ACCEPTED_STOP == 0 ]] || printf 'R7-1-after-%s\tNOT-RUN\tfirst-semantic-red\n' "$ACCEPTED_STOP" >> "$E/not-run.tsv"; jq -n --arg status "$STATUS" --arg reason "$REASON" --arg source "$SRC" --arg artifact "$ART" --argjson runtime "$RUNTIME" --argjson green "$ACCEPTED_GREEN" --argjson stop "$ACCEPTED_STOP" '{turn:"M3-CP4c-2-TB-X2-R7-EXEC",status:$status,reason:$reason,semantic_source:$source,artifact_id:$artifact,runtime_started:($runtime==1),accepted_green:$green,accepted_stop:$stop,selected_r2_branch:"NONE",selected_gate:"NONE",gate_execution_authorized:false,benchmarkExecution:false}' > "$R/summary.json"; cp "$E/execution-ledger.tsv" "$E/not-run.tsv" "$E/postflight.txt" "$R/" 2>/dev/null || true; tar -C "$E" -czf "$R/Directional__M3-CP4c-2-TB-X2-R7-EXEC__raw-evidence.tar.gz" .; sha256sum "$R/Directional__M3-CP4c-2-TB-X2-R7-EXEC__raw-evidence.tar.gz" > "$R/raw-evidence.sha256"; echo "$ex" > "$R/execution-exit-code.txt"; exit "$ex"; }
GH_TOKEN=${GH_TOKEN:?} gh api "repos/$GITHUB_REPOSITORY/actions/artifacts/$ART/zip" > "$W/package.zip" || { REASON=artifact_download_failure; finish 2; }
[[ $(sha256sum "$W/package.zip"|cut -d' ' -f1) == "$OUTER" ]] || { REASON=outer_digest_mismatch; finish 2; }
unzip -q "$W/package.zip" -d "$W/package" || { REASON=artifact_extract_failure; finish 2; }
(cd "$W/package" && sha256sum -c SHA256SUMS > "$E/preflight-sha256sums.txt" 2>&1) || { REASON=internal_manifest_failure; finish 2; }
[[ $(grep -c ': OK$' "$E/preflight-sha256sums.txt") == 28 ]] || { REASON=manifest_count_mismatch; finish 2; }
[[ $(cat "$W/package/metadata/source-commit.txt") == "$SRC" ]] || { REASON=semantic_source_mismatch; finish 2; }
ST="$W/package/source/source-$SRC.tar.gz"; [[ -f $ST && $(sha256sum "$ST"|cut -d' ' -f1) == "$SRC_SHA" ]] || { REASON=source_archive_mismatch; finish 2; }
grep -qx 'exactArithmeticBackend=GMP' "$W/package/metadata/command-boundary.txt" && grep -qx 'runtimeExecution=false' "$W/package/metadata/command-boundary.txt" && grep -qx 'turnBoundary=Code+Build-only' "$W/package/metadata/command-boundary.txt" || { REASON=command_boundary_mismatch; finish 2; }
grep -qi 'gmpxx' "$W/package/metadata/gmp-evidence.txt" && grep -qi 'gmp' "$W/package/metadata/gmp-evidence.txt" || { REASON=gmp_evidence_missing; finish 2; }
for b in directional_surface_cell_authority_kernel_tests directional_surface_cell_producer_tests directional_surface_cell_completion_tests directional_surface_cell_validation_tests directional_compiled_api_tests directional_benchmarks; do [[ -x "$W/package/bin/$b" ]] || { REASON="binary_not_executable:$b"; finish 2; }; done
rm -rf "$GITHUB_WORKSPACE"/* "$GITHUB_WORKSPACE"/.[!.]* "$GITHUB_WORKSPACE"/..?* 2>/dev/null || true
tar -xzf "$ST" -C "$GITHUB_WORKSPACE" || { REASON=source_extract_failure; finish 2; }
test -f "$GITHUB_WORKSPACE/benchmarks/fixtures/bunny_1k_random.obj" || { REASON=fixture_layout_failure; finish 2; }
grep -q "^CMAKE_HOME_DIRECTORY:INTERNAL=$GITHUB_WORKSPACE$" "$W/package/metadata/CMakeCache.txt" || { REASON=compile_source_path_mismatch; finish 2; }
inv "$W/package" "$E/package-before.tsv"; inv "$GITHUB_WORKSPACE" "$E/source-before.tsv"; HAVE_BASE=1
S1="$GITHUB_WORKSPACE/.agents/Directional/Architecture_M3_CP4c1_Required_Green_Selector.txt"; S357="$GITHUB_WORKSPACE/.agents/Directional/Architecture_M3_CP4c2_Required_Green_Selector_357.txt"; S358="$GITHUB_WORKSPACE/.agents/Directional/Architecture_M3_CP4c2_Required_Green_Selector_358.txt"
{ head -n316 "$S1"|sha256sum; head -n346 "$S1"|sha256sum; head -n353 "$S1"|sha256sum; sha256sum "$S1" "$S357" "$S358"; } > "$E/selector-hashes.txt"
mapfile -t hs < <(awk '{print $1}' "$E/selector-hashes.txt"); exp=(601ce2b6a4aa2b0cda971e06e9378ebccba5fa75a9b416407447f7ed3600193c 20d3b0b1400d5cab6af4a339a858c56fb7fd0359fb995a395dad215b20f3e46a 51ff96d72e1c2c88e9407e99737e42ec9093ea238aaf8b1e45ff2559f71ac6a5 e9d88f1196e412e06424294d6be22b32f01c9671ec5e4de119abd3f2fb5afeaa b896d0db7f26aeb0f3513418405efdeccbcf84fb6dc971500c6ddac9e364dc70 6eda3aad83de81fc55d5cd446f80704d604a842f10995789b483291bb64fbe62); for i in {0..5}; do [[ ${hs[$i]:-} == ${exp[$i]} ]] || { REASON="selector_hash_mismatch:$i"; finish 2; }; done
[[ $(wc -l < "$S1") == 355 ]] || { REASON=selector_cardinality_mismatch; finish 2; }
cp "$W/package/metadata/command-boundary.txt" "$E/"; cp "$W/package/metadata/gmp-evidence.txt" "$E/"; printf 'artifact=%s\nouter_sha256=%s\nsemantic_source=%s\nsource_archive_sha256=%s\nselector_count=355\nmanifest_ok=28/28\n' "$ART" "$OUTER" "$SRC" "$SRC_SHA" > "$E/preflight.txt"
while IFS= read -r id; do suite=${id%%.*}; bin=$(owner "$suite") || { REASON="unknown_suite:$suite"; finish 2; }; printf '%s\t%s\n' "$id" "$bin"; done < "$S1" > "$E/owner-census.tsv"
[[ $(wc -l < "$E/owner-census.tsv") == 355 ]] || { REASON=owner_census_failure; finish 2; }
STATUS=RUNNING; REASON=runtime_started; RUNTIME=1
for spec in 'R7-2|SurfaceCutGraph.SemanticDigestIgnoresGaugeRelabelingForTwoRingWitness' 'R7-2|SurfaceCutGraph.SemanticDigestIgnoresGaugeRelabelingForTorusWitness' 'R7-3|ResolvedBranchCorrection.ActualEmbeddedGraphCellularityOracleIsPublishedNonGating' 'R7-4|GlobalTopologyPlan.Cp4c2IndependentNetworkOnlyCellularityOracleIsObservable' 'R7-5|GlobalTopologyPlan.Cp4c2CutGraphFailureLocalizationIsObservable'; do phase=${spec%%|*}; id=${spec#*|}; run1 "$phase" "$id" directional_surface_cell_producer_tests || { STATUS=ORCHESTRATION_RED; REASON="$phase:harness_or_selection_failure"; finish 2; }; if (( RUN_RC < 0 || RUN_RC > 1 )); then STATUS=ORCHESTRATION_RED; REASON="$phase:process_integrity:$RUN_RC"; finish 2; fi; done
ord=0
while IFS= read -r id; do ((ord++)); suite=${id%%.*}; bin=$(owner "$suite") || { STATUS=ORCHESTRATION_RED; REASON="R7-1:unknown_suite:$suite"; finish 2; }; run1 R7-1 "$id" "$bin" "$ord" || { STATUS=ORCHESTRATION_RED; REASON="R7-1:harness_or_selection_failure:$ord"; finish 2; }; if [[ $RUN_RC != 0 ]]; then ACCEPTED_STOP=$ord; STATUS=SEMANTIC_RED; REASON="R7-1:first_red:$ord:$id"; ACCEPTED_GREEN=$((ord-1)); finish 1; fi; ACCEPTED_GREEN=$ord; done < "$S1"
STATUS=SEMANTIC_GREEN; REASON=accepted_355_green; finish 0
