#!/usr/bin/env bash
set -euo pipefail
for v in CANDIDATE_ARTIFACT_ID CANDIDATE_PROVIDER_SHA256 SEMANTIC_SOURCE_SHA SOURCE_ARCHIVE_SHA256 PACKAGE_MANIFEST_SHA256 SELECTOR_SHA256 PREFIX425_SHA256 GENUS_OBJ_SHA256 GENUS_RAWFIELD_SHA256 GENUS_META_SHA256; do : "${!v:?}"; done
log="${RUNNER_TEMP}/m4-cp-scale-tb12-r5-exec.log"; result="${RUNNER_TEMP}/tb12-r5-result"; ev="${RUNNER_TEMP}/tb12-r5-evidence"; pkg="${RUNNER_TEMP}/immutable-package"; src="${RUNNER_TEMP}/semantic-source"; exe="${RUNNER_TEMP}/execution-view"; helper="${GITHUB_WORKSPACE}/.agents/Directional/turn-payloads/m4-cp-scale-tb12-r5-helper.py"
census(){ python3 "$helper" census "$1" "$2"; }; parse(){ python3 "$helper" parse-gtest "$1"; }
rm -rf "$result" "$ev" "$pkg" "$src" "$exe"; mkdir -p "$result" "$ev/preflight" "$ev/postflight" "$ev/raw/focused" "$ev/raw/selector" "$ev/resources/focused" "$ev/resources/selector"
printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"
printf '%s\n' "workflow=$GITHUB_WORKFLOW" "run_id=$GITHUB_RUN_ID" "event_sha=$GITHUB_SHA" "artifact=$CANDIDATE_ARTIFACT_ID" "source=$SEMANTIC_SOURCE_SHA" 'boundary=Test+Benchmark-artifact-only' "started_at=$(date -u +%FT%TZ)" | tee -a "$log"
meta="$ev/artifact-metadata.json"; gh api "repos/${GITHUB_REPOSITORY}/actions/artifacts/${CANDIDATE_ARTIFACT_ID}" > "$meta"; jq -e --argjson id "$CANDIDATE_ARTIFACT_ID" '.id==$id and .expired==false' "$meta" >/dev/null; jq -e --arg d "sha256:${CANDIDATE_PROVIDER_SHA256}" '.digest==$d' "$meta" >/dev/null
zip="${RUNNER_TEMP}/candidate-artifact.zip"; gh api "repos/${GITHUB_REPOSITORY}/actions/artifacts/${CANDIDATE_ARTIFACT_ID}/zip" > "$zip"; test "$(sha256sum "$zip"|awk '{print $1}')" = "$CANDIDATE_PROVIDER_SHA256"
mkdir -p "$pkg"; unzip -q "$zip" -d "$pkg"; test "$(sha256sum "$pkg/SHA256SUMS"|awk '{print $1}')" = "$PACKAGE_MANIFEST_SHA256"; test "$(wc -l < "$pkg/SHA256SUMS"|tr -d ' ')" = 28; (cd "$pkg" && sha256sum -c SHA256SUMS) > "$ev/preflight/package-sha256-check.txt"; census "$pkg" "$ev/package-census-before.tsv"
test "$(cat "$pkg/metadata/source-commit.txt")" = "$SEMANTIC_SOURCE_SHA"; test "$(cat "$pkg/metadata/build-exit-code.txt")" = 0; test "$(cat "$pkg/metadata/preflight-exit-code.txt")" = 0; for f in "$pkg"/metadata/source-status-*.txt; do test ! -s "$f"; done
grep -Fx 'runtimeExecution=false' "$pkg/metadata/command-boundary.txt" >/dev/null; grep -Fx 'turnBoundary=Code+Build-only' "$pkg/metadata/command-boundary.txt" >/dev/null; grep -Fx 'exactArithmeticBackend=GMP' "$pkg/metadata/command-boundary.txt" >/dev/null; grep -F 'libgmpxx.so' "$pkg/metadata/gmp-evidence.txt" >/dev/null; grep -F 'libgmp.so' "$pkg/metadata/gmp-evidence.txt" >/dev/null
arc="$pkg/source/source-${SEMANTIC_SOURCE_SHA}.tar.gz"; test "$(sha256sum "$arc"|awk '{print $1}')" = "$SOURCE_ARCHIVE_SHA256"; mkdir -p "$src"; tar -xzf "$arc" -C "$src"; census "$src" "$ev/source-census-before.tsv"
sel="$src/.agents/Directional/Architecture_M4_CP_SCALE_CB12_Required_Green_Selector_426.txt"; test "$(sha256sum "$sel"|awk '{print $1}')" = "$SELECTOR_SHA256"; python3 "$helper" selector-check "$sel" "$PREFIX425_SHA256"; test -z "$(find "$src/.agents/Directional" -maxdepth 1 -type f -name '*Required_Green_Selector_427.txt' -print -quit)"
fixture="$src/benchmarks/fixtures/milestone-g"; test "$(sha256sum "$fixture/genus_two.obj"|awk '{print $1}')" = "$GENUS_OBJ_SHA256"; test "$(sha256sum "$fixture/genus_two.rawfield"|awk '{print $1}')" = "$GENUS_RAWFIELD_SHA256"; test "$(sha256sum "$fixture/genus_two.fixturemeta.json"|awk '{print $1}')" = "$GENUS_META_SHA256"
for b in directional_surface_cell_authority_kernel_tests directional_surface_cell_producer_tests directional_surface_cell_completion_tests directional_surface_cell_validation_tests directional_compiled_api_tests directional_benchmarks; do p="$pkg/bin/$b"; test -f "$p"; test -x "$p"; test "$(stat -c %a "$p")" = 755; stat -c '%a\t%s\t%n' "$p" >> "$ev/preflight/executable-modes.tsv"; done
for a in "$pkg/lib/libdirectional_core.a" "$pkg/lib/libdirectional_pipeline.a"; do test "$(stat -c %a "$a")" = 644; stat -c '%a\t%s\t%n' "$a" >> "$ev/preflight/library-modes.tsv"; done
ldd "$pkg/bin/directional_surface_cell_producer_tests" > "$ev/preflight/ldd-producer.txt"; ! grep -Fq 'not found' "$ev/preflight/ldd-producer.txt"; grep -F 'libgmpxx.so' "$ev/preflight/ldd-producer.txt" >/dev/null; grep -F 'libgmp.so' "$ev/preflight/ldd-producer.txt" >/dev/null
mkdir -p "$exe/test-data/benchmarks"; cp -a "$pkg/bin" "$exe/bin"; cp -a "$pkg/lib" "$exe/lib"; cp -a "$src/benchmarks/fixtures" "$exe/test-data/benchmarks/fixtures"; census "$src/benchmarks/fixtures" "$ev/source-fixtures-before.tsv"; census "$exe/test-data/benchmarks/fixtures" "$ev/execution-fixtures-before.tsv"; cmp "$ev/source-fixtures-before.tsv" "$ev/execution-fixtures-before.tsv"; census "$exe" "$ev/execution-view-before.tsv"
focused="$ev/focused-owner-map.tsv"; ledger0="$ev/execution-ledger-before.tsv"; python3 "$helper" init-all "$src" "$sel" "$focused" "$ledger0"; test "$(($(wc -l < "$ledger0")-1))" = 436
awk -F '\t' 'NR>1 && $1=="A0"{c++}END{exit c==5?0:1}' "$focused"; awk -F '\t' 'NR>1 && $1=="A"{c++}END{exit c==4?0:1}' "$focused"; awk -F '\t' 'NR>1 && $1=="S5"{c++}END{exit c==1?0:1}' "$focused"; awk -F '\t' 'NR>1 && $2=="SELECTOR426"{c[$5]++}END{printf "authority-kernel=%d\nproducer=%d\ncompletion=%d\nvalidation=%d\n",c["authority-kernel"],c["producer"],c["completion"],c["validation"]}' "$ledger0" > "$ev/selector-owner-census.txt"
printf '%s\n' 'configureExecution=false' 'compileExecution=false' 'relinkExecution=false' 'codeGeneration=false' 'chmodExecution=false' 'packageRepair=false' 'selectorMutation=false' 'benchmarkExecution=false' 'discoveryListHelpVersion=false' > "$ev/execution-prohibitions.txt"
printf '%s\n' "artifact_id=$CANDIDATE_ARTIFACT_ID" "provider_zip_sha256=$CANDIDATE_PROVIDER_SHA256" "semantic_source=$SEMANTIC_SOURCE_SHA" "source_archive_sha256=$SOURCE_ARCHIVE_SHA256" "package_manifest_sha256=$PACKAGE_MANIFEST_SHA256" 'package_manifest_entries=28' 'ledger_rows=436' 'focused_rows=10' 'selector_rows=426' "selector_sha256=$SELECTOR_SHA256" "prefix425_sha256=$PREFIX425_SHA256" "genus_obj_sha256=$GENUS_OBJ_SHA256" "genus_rawfield_sha256=$GENUS_RAWFIELD_SHA256" "genus_meta_sha256=$GENUS_META_SHA256" 'owner_census=30/280/75/41' > "$ev/immutable-input.txt"
postflight(){ (cd "$pkg" && sha256sum -c SHA256SUMS) > "$ev/postflight/package-sha256-check.txt"; test "$(sha256sum "$zip"|awk '{print $1}')" = "$CANDIDATE_PROVIDER_SHA256"; test "$(sha256sum "$pkg/SHA256SUMS"|awk '{print $1}')" = "$PACKAGE_MANIFEST_SHA256"; test "$(sha256sum "$arc"|awk '{print $1}')" = "$SOURCE_ARCHIVE_SHA256"; test "$(sha256sum "$sel"|awk '{print $1}')" = "$SELECTOR_SHA256"; python3 "$helper" selector-check "$sel" "$PREFIX425_SHA256"; test "$(sha256sum "$fixture/genus_two.obj"|awk '{print $1}')" = "$GENUS_OBJ_SHA256"; test "$(sha256sum "$fixture/genus_two.rawfield"|awk '{print $1}')" = "$GENUS_RAWFIELD_SHA256"; test "$(sha256sum "$fixture/genus_two.fixturemeta.json"|awk '{print $1}')" = "$GENUS_META_SHA256"; census "$pkg" "$ev/package-census-after.tsv"; census "$src" "$ev/source-census-after.tsv"; census "$exe" "$ev/execution-view-after.tsv"; census "$src/benchmarks/fixtures" "$ev/source-fixtures-after.tsv"; census "$exe/test-data/benchmarks/fixtures" "$ev/execution-fixtures-after.tsv"; cmp "$ev/package-census-before.tsv" "$ev/package-census-after.tsv"; cmp "$ev/source-census-before.tsv" "$ev/source-census-after.tsv"; cmp "$ev/execution-view-before.tsv" "$ev/execution-view-after.tsv"; cmp "$ev/source-fixtures-before.tsv" "$ev/source-fixtures-after.tsv"; cmp "$ev/execution-fixtures-before.tsv" "$ev/execution-fixtures-after.tsv"; printf '%s\n' 'package_census_equal=true' 'source_census_equal=true' 'execution_view_census_equal=true' 'fixtures_equal=true' 'postflightComplete=true' > "$ev/postflight-immutability.txt"; }
runtime_started=false; runtime_complete=false; semantic_stop=false; orchestration_stop=false; process="$ev/process-ledger.tsv"
finish(){ rc=$?; if [[ $rc -ne 0 && "$runtime_complete" != true ]]; then if [[ "$runtime_started" == true ]]; then printf '%s\n' 'status=ORCHESTRATION_FAILURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"; else printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"; fi; fi; echo "harness_exit=$rc" | tee -a "$log"; }
trap finish EXIT
header='global_ordinal\tphase\tphase_ordinal\tidentity\towner\tbinary\tsource_definition\tcommand\texit\tselected\texecuted\tpassed\tskipped\telapsed_ms\tresult\tstdout\tstderr\tstdout_sha256\tstderr_sha256'; printf '%b\n' "$header" > "$process"
run_one(){ local g=$1 phase=$2 po=$3 id=$4 owner=$5 bin=$6 source_def=$7 bucket=$8 base timefile stdout stderr start end rc s e p k res cmd osh esh; base="$ev/raw/$bucket/global-$(printf %03d "$g")"; timefile="$ev/resources/$bucket/global-$(printf %03d "$g").time.txt"; stdout="${base}.stdout.txt"; stderr="${base}.stderr.txt"; cmd="$exe/bin/$bin --gtest_filter=$id --gtest_color=no"; start=$(date +%s%3N); set +e; (cd "$exe" && /usr/bin/time -v -o "$timefile" "$exe/bin/$bin" --gtest_filter="$id" --gtest_color=no >"$stdout" 2>"$stderr"); rc=$?; set -e; end=$(date +%s%3N); mapfile -t c < <(parse "$stdout"); s=${c[0]:-0}; e=${c[1]:-0}; p=${c[2]:-0}; k=${c[3]:-0}; osh=$(sha256sum "$stdout"|awk '{print $1}'); esh=$(sha256sum "$stderr"|awk '{print $1}'); res=RED; if [[ $s -ne 1 || $e -ne 1 ]]; then res=SELECTION_MISMATCH; elif [[ $rc -eq 0 && $p -eq 1 && $k -eq 0 ]]; then res=PASS; elif [[ $k -ne 0 ]]; then res=SKIP; elif [[ $rc -ge 128 ]]; then res=CRASH; fi; printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$g" "$phase" "$po" "$id" "$owner" "$bin" "$source_def" "$cmd" "$rc" "$s" "$e" "$p" "$k" "$((end-start))" "$res" "${stdout#$ev/}" "${stderr#$ev/}" "$osh" "$esh"; }
append_focused(){ local phase=$1 count=$2 offset=$3 n row res; for n in $(seq 1 "$count"); do IFS=$'\t' read -r _ po id owner bin source_def < <(awk -F '\t' -v ph="$phase" -v n="$n" 'NR>1 && $1==ph && $2==n{print; exit}' "$focused"); row=$(run_one "$((offset+n))" "$phase" "$po" "$id" "$owner" "$bin" "$source_def" focused); printf '%s\n' "$row" >> "$process"; res=$(printf '%s' "$row"|awk -F '\t' '{print $15}'); printf '[TB12-R5 %s %s/%s] %s %s\n' "$phase" "$n" "$count" "$res" "$id"; if [[ $res == RED ]]; then semantic_stop=true; return 1; elif [[ $res != PASS ]]; then orchestration_stop=true; return 1; fi; done; }
runtime_started=true; printf '%s\n' 'status=ORCHESTRATION_FAILURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"
set +e; append_focused A0 5 0; a0_rc=$?; set -e
if [[ $a0_rc -eq 0 ]]; then set +e; append_focused A 4 5; a_rc=$?; set -e; else a_rc=1; fi
if [[ $a0_rc -eq 0 && $a_rc -eq 0 ]]; then set +e; append_focused S5 1 9; s5_rc=$?; set -e; else s5_rc=1; fi
if [[ $a0_rc -eq 0 && $a_rc -eq 0 && $s5_rc -eq 0 ]]; then
  while IFS=$'\t' read -r sord id owner bin source_def; do [[ $sord == ordinal ]] && continue; g=$((10+sord)); row=$(run_one "$g" SELECTOR426 "$sord" "$id" "$owner" "$bin" "$source_def" selector); printf '%s\n' "$row" >> "$process"; res=$(printf '%s' "$row"|awk -F '\t' '{print $15}'); printf '[TB12-R5 selector %s/426] %s %s\n' "$sord" "$res" "$id"; if [[ $res == RED ]]; then semantic_stop=true; break; elif [[ $res != PASS ]]; then orchestration_stop=true; break; fi; done < <(python3 - "$src" "$sel" <<'PY'
import csv,pathlib,re,sys,collections
source=pathlib.Path(sys.argv[1]); selector=pathlib.Path(sys.argv[2]).read_text().splitlines(); cm=(source/'cmake/DirectionalTests.cmake').read_text(); owners={}
m=re.search(r'set\(DIRECTIONAL_SURFACE_CELL_PRODUCER_TEST_SOURCES\s+(.*?)\)',cm,re.S)
for f in re.findall(r'(?m)^\s*(tests/[^\s\)]+\.cpp)\s*$',m.group(1)): owners[f]=('producer','directional_surface_cell_producer_tests')
for binary,owner in {'directional_surface_cell_authority_kernel_tests':'authority-kernel','directional_surface_cell_completion_tests':'completion','directional_surface_cell_validation_tests':'validation'}.items():
 mm=re.search(r'add_executable\(\s*'+re.escape(binary)+r'\s+(.*?)\)',cm,re.S)
 for f in re.findall(r'(?m)^\s*(tests/[^\s\)]+\.cpp)\s*$',mm.group(1)): owners[f]=(owner,binary)
pat=re.compile(r'\bTEST(?:_F|_P)?\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)',re.S); idx=collections.defaultdict(list)
for f,(o,b) in owners.items():
 for s,t in pat.findall((source/f).read_text(errors='replace')): idx[f'{s}.{t}'].append((o,b,f))
for n,i in enumerate(selector,1):
 d=idx[i]; assert len(d)==1; o,b,f=d[0]; print(f'{n}\t{i}\t{o}\t{b}\t{f}')
PY
)
fi
python3 "$helper" finalize "$process" "$ledger0" "$ev/execution-ledger-final.tsv" "$ev/execution-summary.txt"
postflight
pass=$(awk -F= '$1=="pass"{print $2}' "$ev/execution-summary.txt"); a0=$(awk -F= '$1=="a0Pass"{print $2}' "$ev/execution-summary.txt"); aa=$(awk -F= '$1=="aPass"{print $2}' "$ev/execution-summary.txt"); s5=$(awk -F= '$1=="s5Pass"{print $2}' "$ev/execution-summary.txt"); selpass=$(awk -F= '$1=="selectorPass"{print $2}' "$ev/execution-summary.txt"); selexec=$(awk -F= '$1=="selectorExecuted"{print $2}' "$ev/execution-summary.txt"); executed=$(awk -F= '$1=="executed"{print $2}' "$ev/execution-summary.txt")
status=SEMANTIC_RED; semantic_valid=true; completed=true; if [[ "$orchestration_stop" == true ]]; then status=ORCHESTRATION_FAILURE; semantic_valid=false; completed=false; elif [[ $a0 == 5 && $aa == 4 && $s5 == 1 && $selpass == 426 && $selexec == 426 && $executed == 436 ]]; then status=MECHANICALLY_GREEN; fi
runtime_complete=true; printf '%s\n' "status=$status" "semanticLedgerValid=$semantic_valid" "gateA0=$a0/5" "gateA=$aa/4" "s5=$s5/1" "selector426=$selpass/426" "runtime_processes_expected=436" "runtime_processes_actual=$executed" "ledger_unexecuted=$((436-executed))" 'benchmarkExecuted=0' 'postflightComplete=true' 'runtimeStarted=true' "runtimeCompleted=$completed" > "$ev/final-status.txt"; cp "$ev/final-status.txt" "$result/final-status.txt"; cp "$ev/execution-summary.txt" "$result/execution-summary.txt"; cp "$ev/execution-ledger-final.tsv" "$result/execution-ledger-final.tsv"; cp "$ev/immutable-input.txt" "$result/immutable-input.txt"; cp "$ev/selector-owner-census.txt" "$result/selector-owner-census.txt"; cp "$ev/postflight-immutability.txt" "$result/postflight-immutability.txt"; cp "$process" "$result/process-ledger.tsv"
# Preserve S5 stdout/stderr when it executed (global row 10).
cp "$ev/raw/focused/global-010.stdout.txt" "$result/s5.stdout.txt" 2>/dev/null || true; cp "$ev/raw/focused/global-010.stderr.txt" "$result/s5.stderr.txt" 2>/dev/null || true
(cd "$ev" && find . -type f ! -name SHA256SUMS -print0 | LC_ALL=C sort -z | xargs -0 sha256sum > SHA256SUMS); (cd "$ev" && sha256sum -c SHA256SUMS > "$result/evidence-self-check.txt"); (cd "$ev" && zip -q -r "$result/Directional__M4-CP-SCALE-TB12-R5-EXEC__evidence.zip" .); sha256sum "$result/Directional__M4-CP-SCALE-TB12-R5-EXEC__evidence.zip" > "$result/evidence.zip.sha256"; cat "$result/final-status.txt"; if [[ "$status" == ORCHESTRATION_FAILURE ]]; then exit 2; fi
