#!/usr/bin/env bash
set -euo pipefail
source .agents/Directional/turn-payloads/m4-cp-scale-tb11-preflight.sh
runtime_started=false; runtime_complete=false
finish(){ rc=$?; if [[ $rc -ne 0 && "$runtime_complete" != true ]]; then if [[ "$runtime_started" == true ]]; then printf '%s\n' 'status=BLOCKED_INFRASTRUCTURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"; else printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"; fi; fi; echo "harness_exit=$rc" | tee -a "$log"; }
trap finish EXIT
run_one(){ local ord=$1 id=$2 owner=$3 bin=$4 source_def=$5 base timefile stdout stderr start end rc s e p k res cmd; base="$ev/raw/selector/ordinal-$(printf %03d "$ord")"; timefile="$ev/resources/selector/ordinal-$(printf %03d "$ord").time.txt"; stdout="${base}.stdout.txt"; stderr="${base}.stderr.txt"; cmd="$exe/bin/$bin --gtest_filter=$id --gtest_color=no"; start=$(date +%s%3N); set +e; (cd "$exe" && /usr/bin/time -v -o "$timefile" "$exe/bin/$bin" --gtest_filter="$id" --gtest_color=no >"$stdout" 2>"$stderr"); rc=$?; set -e; end=$(date +%s%3N); mapfile -t c < <(parse "$stdout"); s=${c[0]:-0}; e=${c[1]:-0}; p=${c[2]:-0}; k=${c[3]:-0}; res=RED; if [[ $s -ne 1 || $e -ne 1 ]]; then res=SELECTION_MISMATCH; elif [[ $rc -eq 0 && $p -eq 1 && $k -eq 0 ]]; then res=PASS; elif [[ $k -ne 0 ]]; then res=SKIP; elif [[ $rc -ge 128 ]]; then res=CRASH; fi; printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$ord" "$id" "$owner" "$bin" "$source_def" "$cmd" "$rc" "$s" "$e" "$p" "$k" "$((end-start))" "$res" "${stdout#$ev/}" "${stderr#$ev/}"; }
runtime_started=true; printf '%s\n' 'status=BLOCKED_INFRASTRUCTURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"
header='ordinal\tidentity\towner\tbinary\tsource_definition\tcommand\texit\tselected\texecuted\tpassed\tskipped\telapsed_ms\tresult\tstdout\tstderr'; sleg="$ev/selector426-process-ledger.tsv"; printf '%b\n' "$header" > "$sleg"
while IFS=$'\t' read -r ord id owner bin source_def; do [[ $ord == ordinal ]] && continue; row=$(run_one "$ord" "$id" "$owner" "$bin" "$source_def"); printf '%s\n' "$row" >> "$sleg"; res=$(printf '%s' "$row"|awk -F '\t' '{print $13}'); printf '[TB11 selector %s/426] %s %s\n' "$ord" "$res" "$id"; [[ $res == PASS ]] || break; done < "$own"
python3 "$helper" finalize "$sleg" "$ev/selector426-ledger-before.tsv" "$ev/selector426-final-ledger.tsv" "$ev/selector426-summary.txt"; postflight
pass=$(awk -F= '$1=="pass"{print $2}' "$ev/selector426-summary.txt"); executed=$(awk -F= '$1=="executed"{print $2}' "$ev/selector426-summary.txt"); red=$(awk -F= '$1=="red"{print $2}' "$ev/selector426-summary.txt"); skip=$(awk -F= '$1=="skip"{print $2}' "$ev/selector426-summary.txt"); crash=$(awk -F= '$1=="crash"{print $2}' "$ev/selector426-summary.txt"); mismatch=$(awk -F= '$1=="selectionMismatch"{print $2}' "$ev/selector426-summary.txt"); row426=$(awk -F= '$1=="row426"{print $2}' "$ev/selector426-summary.txt"); status=MECHANICALLY_RED; if [[ $pass == 426 && $executed == 426 && $red == 0 && $skip == 0 && $crash == 0 && $mismatch == 0 && $row426 == PASS ]]; then status=MECHANICALLY_GREEN; fi
runtime_complete=true; printf '%s\n' "status=$status" "selector426=$pass/426" "runtime_processes_expected=426" "runtime_processes_actual=$executed" "selector_unexecuted=$((426-executed))" "row426=$row426" 'postflightComplete=true' 'runtimeStarted=true' 'runtimeCompleted=true' > "$ev/final-status.txt"; cp "$ev/final-status.txt" "$result/final-status.txt"; cp "$ev/selector426-summary.txt" "$result/selector426-summary.txt"; cp "$ev/selector426-final-ledger.tsv" "$result/selector426-final-ledger.tsv"; cp "$ev/raw/selector/ordinal-426.stdout.txt" "$result/row426.stdout.txt" 2>/dev/null || true; cp "$ev/raw/selector/ordinal-426.stderr.txt" "$result/row426.stderr.txt" 2>/dev/null || true
(cd "$ev" && find . -type f ! -name SHA256SUMS -print0 | LC_ALL=C sort -z | xargs -0 sha256sum > SHA256SUMS); (cd "$ev" && sha256sum -c SHA256SUMS > "$result/evidence-self-check.txt"); (cd "$ev" && zip -q -r "$result/Directional__M4-CP-SCALE-TB11-EXEC__evidence.zip" .); sha256sum "$result/Directional__M4-CP-SCALE-TB11-EXEC__evidence.zip" > "$result/evidence.zip.sha256"; cat "$result/final-status.txt"
