#!/usr/bin/env bash
set -euo pipefail
: "${CANDIDATE_ARTIFACT_ID:?}"; : "${CANDIDATE_PROVIDER_SHA256:?}"; : "${SEMANTIC_SOURCE_SHA:?}"; : "${SOURCE_ARCHIVE_SHA256:?}"; : "${PACKAGE_MANIFEST_SHA256:?}"; : "${SELECTOR_SHA256:?}"; : "${FOCUSED_IDENTITY:?}"
log="${RUNNER_TEMP}/m4-cp-scale-tb8-exec.log"; result="${RUNNER_TEMP}/tb8-result"; evidence="${RUNNER_TEMP}/tb8-evidence"; package="${RUNNER_TEMP}/immutable-package"; source_root="${RUNNER_TEMP}/semantic-source"; execution="${RUNNER_TEMP}/execution-view"; helper="${GITHUB_WORKSPACE}/.agents/Directional/turn-payloads/m4-cp-scale-tb8-helper.py"
rm -rf "$result" "$evidence" "$package" "$source_root" "$execution"
mkdir -p "$result" "$evidence/preflight" "$evidence/postflight" "$evidence/raw/focused" "$evidence/raw/selector" "$evidence/resources/focused" "$evidence/resources/selector"
printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"
runtime_started=false; runtime_complete=false
finish(){ rc=$?; if [[ "$rc" -ne 0 && "$runtime_complete" != true ]]; then if [[ "$runtime_started" == true ]]; then printf '%s\n' 'status=BLOCKED_INFRASTRUCTURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"; else printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"; fi; fi; echo "harness_exit=${rc}" | tee -a "$log"; }
trap finish EXIT
census_tree(){ python3 "$helper" census "$1" "$2"; }; parse_gtest(){ python3 "$helper" parse-gtest "$1"; }
{
  echo "workflow=${GITHUB_WORKFLOW}"; echo "run_id=${GITHUB_RUN_ID}"; echo "event=${GITHUB_EVENT_NAME}"; echo "event_sha=${GITHUB_SHA}"; echo "candidate_artifact_id=${CANDIDATE_ARTIFACT_ID}"; echo "candidate_provider_sha256=${CANDIDATE_PROVIDER_SHA256}"; echo "semantic_source_sha=${SEMANTIC_SOURCE_SHA}"; echo "selector_sha256=${SELECTOR_SHA256}"; echo "focused_identity=${FOCUSED_IDENTITY}"; echo 'runtime_boundary=Test+Benchmark artifact-only'; echo "started_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)";
} | tee -a "$log"
meta="$evidence/artifact-metadata.json"; gh api "repos/${GITHUB_REPOSITORY}/actions/artifacts/${CANDIDATE_ARTIFACT_ID}" > "$meta"
jq -e --argjson id "$CANDIDATE_ARTIFACT_ID" '.id==$id and .expired==false' "$meta" >/dev/null; jq -e --arg digest "sha256:${CANDIDATE_PROVIDER_SHA256}" '.digest==$digest' "$meta" >/dev/null
candidate_zip="${RUNNER_TEMP}/candidate-artifact.zip"; gh api "repos/${GITHUB_REPOSITORY}/actions/artifacts/${CANDIDATE_ARTIFACT_ID}/zip" > "$candidate_zip"; test "$(sha256sum "$candidate_zip"|awk '{print $1}')" = "$CANDIDATE_PROVIDER_SHA256"
mkdir -p "$package"; unzip -q "$candidate_zip" -d "$package"
test -f "$package/SHA256SUMS"; test "$(sha256sum "$package/SHA256SUMS"|awk '{print $1}')" = "$PACKAGE_MANIFEST_SHA256"; test "$(wc -l < "$package/SHA256SUMS"|tr -d ' ')" = 26; (cd "$package" && sha256sum -c SHA256SUMS) > "$evidence/preflight/package-sha256-check.txt"; census_tree "$package" "$evidence/package-census-before.tsv"
test "$(cat "$package/metadata/source-commit.txt")" = "$SEMANTIC_SOURCE_SHA"; test "$(cat "$package/metadata/build-exit-code.txt")" = 0; test "$(cat "$package/metadata/preflight-exit-code.txt")" = 0; for f in "$package"/metadata/source-status-*.txt; do test ! -s "$f"; done
grep -Fx 'runtimeExecution=false' "$package/metadata/command-boundary.txt" >/dev/null; grep -Fx 'turnBoundary=Code+Build-only' "$package/metadata/command-boundary.txt" >/dev/null; grep -Fx 'exactArithmeticBackend=GMP' "$package/metadata/command-boundary.txt" >/dev/null; grep -F 'libgmpxx' "$package/metadata/gmp-evidence.txt" >/dev/null; grep -F 'libgmp.so' "$package/metadata/gmp-evidence.txt" >/dev/null
source_archive="$package/source/source-${SEMANTIC_SOURCE_SHA}.tar.gz"; test -f "$source_archive"; test "$(sha256sum "$source_archive"|awk '{print $1}')" = "$SOURCE_ARCHIVE_SHA256"; mkdir -p "$source_root"; tar -xzf "$source_archive" -C "$source_root"; census_tree "$source_root" "$evidence/source-census-before.tsv"
selector="$source_root/.agents/Directional/Architecture_M4_CP_SCALE_CB8_Required_Green_Selector_425.txt"; test -f "$selector"; test "$(sha256sum "$selector"|awk '{print $1}')" = "$SELECTOR_SHA256"; python3 "$helper" selector-check "$selector"
owner_map="$evidence/selector425-owner-map.tsv"; python3 "$helper" owner-map "$source_root" "$selector" "$owner_map"; python3 "$helper" focus-owner "$source_root" "$evidence/focused-owner.txt"; grep -Fx "identity=${FOCUSED_IDENTITY}" "$evidence/focused-owner.txt" >/dev/null; grep -Fx 'binary=directional_surface_cell_producer_tests' "$evidence/focused-owner.txt" >/dev/null
awk -F '\t' 'NR>1 {c[$3]++} END {printf "authority-kernel=%d\nproducer=%d\ncompletion=%d\nvalidation=%d\n",c["authority-kernel"],c["producer"],c["completion"],c["validation"]}' "$owner_map" > "$evidence/owner-census.txt"
for b in directional_surface_cell_authority_kernel_tests directional_surface_cell_producer_tests directional_surface_cell_completion_tests directional_surface_cell_validation_tests; do p="$package/bin/$b"; test -f "$p"; test -x "$p"; test "$(stat -c '%a' "$p")" = 755; ldd "$p" > "$evidence/preflight/ldd-${b}.txt"; ! grep -Fq 'not found' "$evidence/preflight/ldd-${b}.txt"; done
grep -F 'libgmpxx.so' "$evidence/preflight/ldd-directional_surface_cell_producer_tests.txt" >/dev/null; grep -F 'libgmp.so' "$evidence/preflight/ldd-directional_surface_cell_producer_tests.txt" >/dev/null
mkdir -p "$execution/test-data/benchmarks"; cp -a "$package/bin" "$execution/bin"; cp -a "$package/lib" "$execution/lib"; cp -a "$source_root/benchmarks/fixtures" "$execution/test-data/benchmarks/fixtures"; census_tree "$source_root/benchmarks/fixtures" "$evidence/source-fixtures-census.tsv"; census_tree "$execution/test-data/benchmarks/fixtures" "$evidence/execution-fixtures-census.tsv"; cmp "$evidence/source-fixtures-census.tsv" "$evidence/execution-fixtures-census.tsv"; census_tree "$execution" "$evidence/execution-view-before.tsv"
printf '%s\n' 'configureExecution=false' 'compileExecution=false' 'relinkExecution=false' 'repairExecution=false' 'generatedDiscovery=false' 'mutationExecution=false' 'benchmarkExecution=false' > "$evidence/execution-prohibitions.txt"
printf '%s\n' "artifact_id=${CANDIDATE_ARTIFACT_ID}" "provider_zip_sha256=${CANDIDATE_PROVIDER_SHA256}" "semantic_source=${SEMANTIC_SOURCE_SHA}" "source_archive_sha256=${SOURCE_ARCHIVE_SHA256}" "package_manifest_sha256=${PACKAGE_MANIFEST_SHA256}" 'package_manifest_entries=26' 'selector_rows=425' "selector_sha256=${SELECTOR_SHA256}" 'owner_census=30/279/75/41' 'runtimeExecution_before_tb=false' > "$evidence/immutable-input.txt"
runtime_started=true; printf '%s\n' 'status=BLOCKED_INFRASTRUCTURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"
run_one(){
  local kind="$1" ordinal="$2" identity="$3" owner="$4" binary="$5" source_definition="$6" base stdout stderr timefile command started ended elapsed exit_code selected executed passed skipped row_result
  if [[ "$kind" == focused ]]; then base="$evidence/raw/focused/focused"; timefile="$evidence/resources/focused/focused.time.txt"; else base="$evidence/raw/selector/ordinal-$(printf '%03d' "$ordinal")"; timefile="$evidence/resources/selector/ordinal-$(printf '%03d' "$ordinal").time.txt"; fi
  stdout="${base}.stdout.txt"; stderr="${base}.stderr.txt"; command="$execution/bin/$binary --gtest_filter=$identity --gtest_color=no"; started="$(date +%s%3N)"; set +e; (cd "$execution" && /usr/bin/time -v -o "$timefile" "$execution/bin/$binary" --gtest_filter="$identity" --gtest_color=no >"$stdout" 2>"$stderr"); exit_code=$?; set -e; ended="$(date +%s%3N)"; elapsed=$((ended-started)); mapfile -t counts < <(parse_gtest "$stdout"); selected="${counts[0]:-0}"; executed="${counts[1]:-0}"; passed="${counts[2]:-0}"; skipped="${counts[3]:-0}"; row_result=RED
  if [[ "$selected" -ne 1 || "$executed" -ne 1 ]]; then row_result=SELECTION_MISMATCH; elif [[ "$exit_code" -eq 0 && "$passed" -eq 1 && "$skipped" -eq 0 ]]; then row_result=PASS; elif [[ "$skipped" -ne 0 ]]; then row_result=SKIP; elif [[ "$exit_code" -ge 128 ]]; then row_result=CRASH; fi
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$ordinal" "$identity" "$owner" "$binary" "$source_definition" "$command" "$exit_code" "$selected" "$executed" "$passed" "$skipped" "$elapsed" "$row_result" "${stdout#$evidence/}" "${stderr#$evidence/}"
}
focused_ledger="$evidence/focused-process-ledger.tsv"; printf 'ordinal\tidentity\towner\tbinary\tsource_definition\tcommand\texit\tselected\texecuted\tpassed\tskipped\telapsed_ms\tresult\tstdout\tstderr\n' > "$focused_ledger"; focus_source="$(awk -F= '$1=="source_definition"{print $2}' "$evidence/focused-owner.txt")"; run_one focused 0 "$FOCUSED_IDENTITY" producer directional_surface_cell_producer_tests "$focus_source" >> "$focused_ledger"; focus_result="$(awk -F '\t' 'NR==2 {print $13}' "$focused_ledger")"
if [[ "$focus_result" == PASS ]]; then if ! python3 "$helper" focused-receipt "$evidence/raw/focused/focused.stdout.txt" "$evidence/focused-structured-receipt.txt"; then focus_result=RED; fi; fi
selector_ledger="$evidence/selector425-process-ledger.tsv"; printf 'ordinal\tidentity\towner\tbinary\tsource_definition\tcommand\texit\tselected\texecuted\tpassed\tskipped\telapsed_ms\tresult\tstdout\tstderr\n' > "$selector_ledger"; first_unexecuted=1
if [[ "$focus_result" == PASS ]]; then while IFS=$'\t' read -r ordinal identity owner binary source_definition; do [[ "$ordinal" == ordinal ]] && continue; row="$(run_one selector "$ordinal" "$identity" "$owner" "$binary" "$source_definition")"; printf '%s\n' "$row" >> "$selector_ledger"; row_result="$(printf '%s\n' "$row"|awk -F '\t' '{print $13}')"; printf '[TB8 selector %s/425] %s %s\n' "$ordinal" "$row_result" "$identity"; first_unexecuted=$((ordinal+1)); [[ "$row_result" == PASS ]] || break; done < "$owner_map"; fi
python3 "$helper" selector-summary "$selector_ledger" "$evidence/selector425-summary.txt"; if [[ "$first_unexecuted" -le 425 ]]; then python3 "$helper" remainder "$owner_map" "$first_unexecuted" "$evidence/selector425-unexecuted.tsv"; else printf 'ordinal\tidentity\tstatus\n' > "$evidence/selector425-unexecuted.tsv"; fi
# Immutable postflight runs even after a semantic anomaly.
(cd "$package" && sha256sum -c SHA256SUMS) > "$evidence/postflight/package-sha256-check.txt"; test "$(sha256sum "$package/SHA256SUMS"|awk '{print $1}')" = "$PACKAGE_MANIFEST_SHA256"; test "$(sha256sum "$source_archive"|awk '{print $1}')" = "$SOURCE_ARCHIVE_SHA256"; test "$(sha256sum "$selector"|awk '{print $1}')" = "$SELECTOR_SHA256"; test "$(cat "$package/metadata/source-commit.txt")" = "$SEMANTIC_SOURCE_SHA"; census_tree "$package" "$evidence/package-census-after.tsv"; census_tree "$source_root" "$evidence/source-census-after.tsv"; census_tree "$execution" "$evidence/execution-view-after.tsv"; cmp "$evidence/package-census-before.tsv" "$evidence/package-census-after.tsv"; cmp "$evidence/source-census-before.tsv" "$evidence/source-census-after.tsv"; cmp "$evidence/execution-view-before.tsv" "$evidence/execution-view-after.tsv"
printf '%s\n' 'package_census_equal=true' 'source_census_equal=true' 'execution_view_census_equal=true' 'package_manifest_verified=true' "semantic_source=${SEMANTIC_SOURCE_SHA}" "selector_sha256=${SELECTOR_SHA256}" > "$evidence/postflight-immutability.txt"
passn="$(awk -F= '$1=="pass"{print $2}' "$evidence/selector425-summary.txt")"; executedn="$(awk -F= '$1=="executed"{print $2}' "$evidence/selector425-summary.txt")"; unexecutedn="$(awk -F= '$1=="unexecuted"{print $2}' "$evidence/selector425-summary.txt")"; ord_ok="$(awk -F= '$1=="ordinalContiguous"{print $2}' "$evidence/selector425-summary.txt")"; authn="$(awk -F= '$1=="authorityKernelPassed"{print $2}' "$evidence/selector425-summary.txt")"; prodn="$(awk -F= '$1=="producerPassed"{print $2}' "$evidence/selector425-summary.txt")"; compn="$(awk -F= '$1=="completionPassed"{print $2}' "$evidence/selector425-summary.txt")"; valn="$(awk -F= '$1=="validationPassed"{print $2}' "$evidence/selector425-summary.txt")"; status=MECHANICALLY_RED
if [[ "$focus_result" == PASS && "$passn" == 425 && "$executedn" == 425 && "$unexecutedn" == 0 && "$ord_ok" == true && "$authn/$prodn/$compn/$valn" == 30/279/75/41 ]]; then status=MECHANICALLY_GREEN; fi
runtime_complete=true; printf '%s\n' "status=${status}" "focused=${focus_result}" "selector425=${passn}/425" 'runtime_processes_expected=426' "runtime_selector_processes_actual=${executedn}" "runtime_processes_actual=$((executedn+1))" "selector_unexecuted=${unexecutedn}" 'postflightComplete=true' 'runtimeStarted=true' 'runtimeCompleted=true' > "$evidence/final-status.txt"; cp "$evidence/final-status.txt" "$result/final-status.txt"; cp "$evidence/selector425-summary.txt" "$result/selector425-summary.txt"; cp "$evidence/focused-structured-receipt.txt" "$result/focused-structured-receipt.txt" 2>/dev/null || true
(cd "$evidence" && find . -type f ! -name SHA256SUMS -print0 | LC_ALL=C sort -z | xargs -0 sha256sum > SHA256SUMS); (cd "$evidence" && sha256sum -c SHA256SUMS > "$result/evidence-manifest-check.txt"); (cd "$evidence" && zip -q -r "$result/Directional__M4-CP-SCALE-TB8-EXEC__evidence.zip" .); sha256sum "$result/Directional__M4-CP-SCALE-TB8-EXEC__evidence.zip" > "$result/evidence.zip.sha256"; cat "$result/final-status.txt"
