#!/usr/bin/env bash
for v in CANDIDATE_ARTIFACT_ID CANDIDATE_PROVIDER_SHA256 SEMANTIC_SOURCE_SHA SOURCE_ARCHIVE_SHA256 PACKAGE_MANIFEST_SHA256 SELECTOR_SHA256 PREFIX424_SHA256 FOCUSED_IDENTITY; do : "${!v:?}"; done
log="${RUNNER_TEMP}/m4-cp-scale-tb9-exec.log"; result="${RUNNER_TEMP}/tb9-result"; ev="${RUNNER_TEMP}/tb9-evidence"; pkg="${RUNNER_TEMP}/immutable-package"; src="${RUNNER_TEMP}/semantic-source"; exe="${RUNNER_TEMP}/execution-view"; helper="${GITHUB_WORKSPACE}/.agents/Directional/turn-payloads/m4-cp-scale-tb9-helper.py"
census(){ python3 "$helper" census "$1" "$2"; }; parse(){ python3 "$helper" parse-gtest "$1"; }
rm -rf "$result" "$ev" "$pkg" "$src" "$exe"; mkdir -p "$result" "$ev/preflight" "$ev/postflight" "$ev/raw/focused" "$ev/raw/selector" "$ev/resources/focused" "$ev/resources/selector"
printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"
printf '%s\n' "workflow=$GITHUB_WORKFLOW" "run_id=$GITHUB_RUN_ID" "event_sha=$GITHUB_SHA" "artifact=$CANDIDATE_ARTIFACT_ID" "source=$SEMANTIC_SOURCE_SHA" 'boundary=Test+Benchmark-artifact-only' "started_at=$(date -u +%FT%TZ)" | tee -a "$log"
meta="$ev/artifact-metadata.json"; gh api "repos/${GITHUB_REPOSITORY}/actions/artifacts/${CANDIDATE_ARTIFACT_ID}" > "$meta"; jq -e --argjson id "$CANDIDATE_ARTIFACT_ID" '.id==$id and .expired==false' "$meta" >/dev/null; jq -e --arg d "sha256:${CANDIDATE_PROVIDER_SHA256}" '.digest==$d' "$meta" >/dev/null
zip="${RUNNER_TEMP}/candidate-artifact.zip"; gh api "repos/${GITHUB_REPOSITORY}/actions/artifacts/${CANDIDATE_ARTIFACT_ID}/zip" > "$zip"; test "$(sha256sum "$zip"|awk '{print $1}')" = "$CANDIDATE_PROVIDER_SHA256"
mkdir -p "$pkg"; unzip -q "$zip" -d "$pkg"; test "$(sha256sum "$pkg/SHA256SUMS"|awk '{print $1}')" = "$PACKAGE_MANIFEST_SHA256"; test "$(wc -l < "$pkg/SHA256SUMS"|tr -d ' ')" = 28; (cd "$pkg" && sha256sum -c SHA256SUMS) > "$ev/preflight/package-sha256-check.txt"; census "$pkg" "$ev/package-census-before.tsv"
test "$(cat "$pkg/metadata/source-commit.txt")" = "$SEMANTIC_SOURCE_SHA"; test "$(cat "$pkg/metadata/build-exit-code.txt")" = 0; test "$(cat "$pkg/metadata/preflight-exit-code.txt")" = 0; for f in "$pkg"/metadata/source-status-*.txt; do test ! -s "$f"; done
grep -Fx 'runtimeExecution=false' "$pkg/metadata/command-boundary.txt" >/dev/null; grep -Fx 'turnBoundary=Code+Build-only' "$pkg/metadata/command-boundary.txt" >/dev/null; grep -Fx 'exactArithmeticBackend=GMP' "$pkg/metadata/command-boundary.txt" >/dev/null; grep -F 'libgmpxx.so' "$pkg/metadata/gmp-evidence.txt" >/dev/null; grep -F 'libgmp.so' "$pkg/metadata/gmp-evidence.txt" >/dev/null
arc="$pkg/source/source-${SEMANTIC_SOURCE_SHA}.tar.gz"; test "$(sha256sum "$arc"|awk '{print $1}')" = "$SOURCE_ARCHIVE_SHA256"; mkdir -p "$src"; tar -xzf "$arc" -C "$src"; census "$src" "$ev/source-census-before.tsv"
sel="$src/.agents/Directional/Architecture_M4_CP_SCALE_CB8_Required_Green_Selector_425.txt"; test "$(sha256sum "$sel"|awk '{print $1}')" = "$SELECTOR_SHA256"; python3 "$helper" selector-check "$sel" "$PREFIX424_SHA256"; ! find "$src/.agents/Directional" -maxdepth 1 -type f -name '*Required_Green_Selector_426.txt' -print -quit | grep -q .
own="$ev/selector425-owner-map.tsv"; focus="$ev/focused-owner.txt"; python3 "$helper" owner-map "$src" "$sel" "$own" "$focus"; awk -F '\t' 'NR>1{c[$3]++}END{printf "authority-kernel=%d\nproducer=%d\ncompletion=%d\nvalidation=%d\n",c["authority-kernel"],c["producer"],c["completion"],c["validation"]}' "$own" > "$ev/owner-census.txt"
for b in directional_surface_cell_authority_kernel_tests directional_surface_cell_producer_tests directional_surface_cell_completion_tests directional_surface_cell_validation_tests directional_compiled_api_tests directional_benchmarks; do p="$pkg/bin/$b"; test -f "$p"; test -x "$p"; test "$(stat -c %a "$p")" = 755; stat -c '%a\t%s\t%n' "$p" >> "$ev/preflight/executable-modes.tsv"; done
ldd "$pkg/bin/directional_surface_cell_producer_tests" > "$ev/preflight/ldd-producer.txt"; ! grep -Fq 'not found' "$ev/preflight/ldd-producer.txt"; grep -F 'libgmpxx.so' "$ev/preflight/ldd-producer.txt" >/dev/null; grep -F 'libgmp.so' "$ev/preflight/ldd-producer.txt" >/dev/null
mkdir -p "$exe/test-data/benchmarks"; cp -a "$pkg/bin" "$exe/bin"; cp -a "$pkg/lib" "$exe/lib"; cp -a "$src/benchmarks/fixtures" "$exe/test-data/benchmarks/fixtures"; census "$src/benchmarks/fixtures" "$ev/source-fixtures-before.tsv"; census "$exe/test-data/benchmarks/fixtures" "$ev/execution-fixtures-before.tsv"; cmp "$ev/source-fixtures-before.tsv" "$ev/execution-fixtures-before.tsv"; census "$exe" "$ev/execution-view-before.tsv"
printf '%s\n' 'configureExecution=false' 'compileExecution=false' 'relinkExecution=false' 'codeGeneration=false' 'chmodExecution=false' 'packageRepair=false' 'selectorMutation=false' 'benchmarkExecution=false' 'discoveryListHelpVersion=false' > "$ev/execution-prohibitions.txt"
printf '%s\n' "artifact_id=$CANDIDATE_ARTIFACT_ID" "provider_zip_sha256=$CANDIDATE_PROVIDER_SHA256" "semantic_source=$SEMANTIC_SOURCE_SHA" "source_archive_sha256=$SOURCE_ARCHIVE_SHA256" "package_manifest_sha256=$PACKAGE_MANIFEST_SHA256" 'package_manifest_entries=28' 'selector_rows=425' "selector_sha256=$SELECTOR_SHA256" "prefix424_sha256=$PREFIX424_SHA256" 'owner_census=30/279/75/41' > "$ev/immutable-input.txt"
postflight(){ (cd "$pkg" && sha256sum -c SHA256SUMS) > "$ev/postflight/package-sha256-check.txt"; test "$(sha256sum "$zip"|awk '{print $1}')" = "$CANDIDATE_PROVIDER_SHA256"; test "$(sha256sum "$pkg/SHA256SUMS"|awk '{print $1}')" = "$PACKAGE_MANIFEST_SHA256"; test "$(sha256sum "$arc"|awk '{print $1}')" = "$SOURCE_ARCHIVE_SHA256"; test "$(sha256sum "$sel"|awk '{print $1}')" = "$SELECTOR_SHA256"; python3 "$helper" selector-check "$sel" "$PREFIX424_SHA256"; census "$pkg" "$ev/package-census-after.tsv"; census "$src" "$ev/source-census-after.tsv"; census "$exe" "$ev/execution-view-after.tsv"; census "$src/benchmarks/fixtures" "$ev/source-fixtures-after.tsv"; census "$exe/test-data/benchmarks/fixtures" "$ev/execution-fixtures-after.tsv"; cmp "$ev/package-census-before.tsv" "$ev/package-census-after.tsv"; cmp "$ev/source-census-before.tsv" "$ev/source-census-after.tsv"; cmp "$ev/execution-view-before.tsv" "$ev/execution-view-after.tsv"; cmp "$ev/source-fixtures-before.tsv" "$ev/source-fixtures-after.tsv"; cmp "$ev/execution-fixtures-before.tsv" "$ev/execution-fixtures-after.tsv"; printf '%s\n' 'package_census_equal=true' 'source_census_equal=true' 'execution_view_census_equal=true' 'fixtures_equal=true' 'postflightComplete=true' > "$ev/postflight-immutability.txt"; }
