#!/usr/bin/env bash
set -euo pipefail
source .agents/Directional/turn-payloads/m4-cp-scale-tb10-preflight.sh
runtime_started=false; runtime_complete=false
finish(){ rc=$?; if [[ $rc -ne 0 && "$runtime_complete" != true ]]; then if [[ "$runtime_started" == true ]]; then printf '%s\n' 'status=BLOCKED_INFRASTRUCTURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"; else printf '%s\n' 'status=BLOCKED_PRE_RUNTIME' 'runtimeStarted=false' 'runtimeCompleted=false' > "$result/final-status.txt"; fi; fi; echo "harness_exit=$rc" | tee -a "$log"; }
trap finish EXIT
run_one(){ local kind=$1 ord=$2 id=$3 owner=$4 bin=$5 source_def=$6 base timefile stdout stderr start end rc s e p k res cmd; if [[ $kind == focused ]]; then base="$ev/raw/focused/focused"; timefile="$ev/resources/focused/focused.time.txt"; else base="$ev/raw/selector/ordinal-$(printf %03d "$ord")"; timefile="$ev/resources/selector/ordinal-$(printf %03d "$ord").time.txt"; fi; stdout="${base}.stdout.txt"; stderr="${base}.stderr.txt"; cmd="$exe/bin/$bin --gtest_filter=$id --gtest_color=no"; start=$(date +%s%3N); set +e; (cd "$exe" && /usr/bin/time -v -o "$timefile" "$exe/bin/$bin" --gtest_filter="$id" --gtest_color=no >"$stdout" 2>"$stderr"); rc=$?; set -e; end=$(date +%s%3N); mapfile -t c < <(parse "$stdout"); s=${c[0]:-0}; e=${c[1]:-0}; p=${c[2]:-0}; k=${c[3]:-0}; res=RED; if [[ $s -ne 1 || $e -ne 1 ]]; then res=SELECTION_MISMATCH; elif [[ $rc -eq 0 && $p -eq 1 && $k -eq 0 ]]; then res=PASS; elif [[ $k -ne 0 ]]; then res=SKIP; elif [[ $rc -ge 128 ]]; then res=CRASH; fi; printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$ord" "$id" "$owner" "$bin" "$source_def" "$cmd" "$rc" "$s" "$e" "$p" "$k" "$((end-start))" "$res" "${stdout#$ev/}" "${stderr#$ev/}"; }
runtime_started=true; printf '%s\n' 'status=BLOCKED_INFRASTRUCTURE' 'runtimeStarted=true' 'runtimeCompleted=false' > "$result/final-status.txt"
header='ordinal\tidentity\towner\tbinary\tsource_definition\tcommand\texit\tselected\texecuted\tpassed\tskipped\telapsed_ms\tresult\tstdout\tstderr'; fleg="$ev/focused-process-ledger.tsv"; printf '%b\n' "$header" > "$fleg"; fsrc=$(awk -F= '$1=="source_definition"{print $2}' "$focus"); run_one focused 0 "$FOCUSED_IDENTITY" producer directional_surface_cell_producer_tests "$fsrc" >> "$fleg"; fres=$(awk -F '\t' 'NR==2{print $13}' "$fleg"); if [[ $fres == PASS ]] && ! python3 "$helper" receipt "$ev/raw/focused/focused.stdout.txt" "$ev/focused-structured-receipt.txt"; then fres=RED; fi
sleg="$ev/selector425-process-ledger.tsv"; printf '%b\n' "$header" > "$sleg"
if [[ $fres == PASS ]]; then while IFS=$'\t' read -r ord id owner bin source_def; do [[ $ord == ordinal ]] && continue; row=$(run_one selector "$ord" "$id" "$owner" "$bin" "$source_def"); printf '%s\n' "$row" >> "$sleg"; printf '[TB10 selector %s/425] %s %s\n' "$ord" "$(printf '%s' "$row"|awk -F '\t' '{print $13}')" "$id"; done < "$own"; else python3 "$helper" remainder "$own" "$ev/selector425-unexecuted.tsv"; fi
python3 "$helper" summary "$sleg" "$ev/selector425-summary.txt"; postflight
pass=$(awk -F= '$1=="pass"{print $2}' "$ev/selector425-summary.txt"); executed=$(awk -F= '$1=="executed"{print $2}' "$ev/selector425-summary.txt"); red=$(awk -F= '$1=="red"{print $2}' "$ev/selector425-summary.txt"); skip=$(awk -F= '$1=="skip"{print $2}' "$ev/selector425-summary.txt"); crash=$(awk -F= '$1=="crash"{print $2}' "$ev/selector425-summary.txt"); mismatch=$(awk -F= '$1=="selectionMismatch"{print $2}' "$ev/selector425-summary.txt"); status=MECHANICALLY_RED; if [[ $fres == PASS && $pass == 425 && $executed == 425 && $red == 0 && $skip == 0 && $crash == 0 && $mismatch == 0 ]]; then status=MECHANICALLY_GREEN; fi
runtime_complete=true; printf '%s\n' "status=$status" "focused=$fres" "selector425=$pass/425" 'runtime_processes_expected=426' "runtime_selector_processes_actual=$executed" "runtime_processes_actual=$((executed+1))" "selector_unexecuted=$((425-executed))" 'postflightComplete=true' 'runtimeStarted=true' 'runtimeCompleted=true' > "$ev/final-status.txt"; cp "$ev/final-status.txt" "$result/final-status.txt"; cp "$ev/selector425-summary.txt" "$result/selector425-summary.txt"; cp "$ev/focused-structured-receipt.txt" "$result/" 2>/dev/null || true
(cd "$ev" && find . -type f ! -name SHA256SUMS -print0 | LC_ALL=C sort -z | xargs -0 sha256sum > SHA256SUMS); (cd "$ev" && sha256sum -c SHA256SUMS > "$result/evidence-self-check.txt"); (cd "$ev" && zip -q -r "$result/Directional__M4-CP-SCALE-TB10-EXEC__evidence.zip" .); sha256sum "$result/Directional__M4-CP-SCALE-TB10-EXEC__evidence.zip" > "$result/evidence.zip.sha256"; cat "$result/final-status.txt"
