#include "CliCommands.h"

#include <ostream>

namespace directional::cli {

void print_usage(std::ostream &stream) {
  stream
      << "Directional native command line interface\n\n"
      << "Usage:\n"
      << "  directional info\n"
      << "  directional cross-field <input.obj|input.off> <output-field> [options]\n"
      << "  directional convert-field <input-field> <output-field> [options]\n"
      << "  directional compare-fields <input.obj|input.off> <first-field> <second-field> [options]\n"
      << "  directional simplify <input.obj|input.off> <output.obj|output.off> [options]\n"
      << "  directional remesh <input.obj|input.off> <output.obj|output.off> [options]\n"
      << "  directional --version\n"
      << "  directional --help\n\n"
      << "Field formats:\n"
      << "  crossfield/neurcross  .vec, .txt, .neurcross; rows contain alpha and beta (six values).\n"
      << "  rosy        .rosy; two-line count/degree header and one alpha vector per face.\n"
      << "  rawfield    .rawfield; degree/count header and 3 * degree values per face.\n\n"
      << "Commands:\n"
      << "  info           Show native library build information.\n"
      << "  cross-field    Extract a smooth face-based 4-RoSy field.\n"
      << "  convert-field  Convert between crossfield, rosy, and rawfield formats.\n"
      << "  compare-fields Compare two face-aligned cross fields and write a heatmap.\n"
      << "  simplify       Simplify a triangle mesh using QEM or NVF-guided constrained QEM.\n"
      << "  remesh         Remesh a triangle mesh, extracting a cross field when none is supplied.\n\n"
      << "cross-field options:\n"
      << "  --method <smooth|regularized-curvature>\n"
      << "  --output-format <auto|crossfield|neurcross|rosy|rawfield>\n"
      << "  --proxy-fidelity <value>       Proxy positional fidelity (default 1).\n"
      << "  --proxy-smoothness <value>     Proxy biharmonic weight (default 0.01).\n"
      << "  --no-preserve-boundary         Allow proxy boundary vertices to move.\n"
      << "  --no-preserve-sharp-features   Allow proxy sharp-feature vertices to move.\n"
      << "  --no-feature-aware-corner-normals\n"
      << "                                  Use globally averaged vertex normals.\n"
      << "  --field-smoothness <value>     Field smoothness weight (default 1).\n"
      << "  --curvature-alignment <value>  Curvature alignment weight (default 1).\n"
      << "  --boundary-alignment <value>   Boundary-edge alignment weight (default 1).\n"
      << "  --sharp-feature-alignment <v>  Sharp-edge alignment weight (default 1).\n"
      << "  --curvature-min-confidence <v> Ignore weaker curvature targets.\n"
      << "  --curvature-confidence-exponent <value>\n"
      << "  --curvature-smoothing-iterations <count>\n"
      << "  --curvature-sharp-angle <degrees>\n"
      << "  --smooth-curvature-across-features\n"
      << "  --no-normalize-directions  Preserve computed direction magnitudes.\n"
      << "  --no-normalize             Backward-compatible alias.\n"
      << "  --no-matching              Skip edge matching and singularity analysis.\n"
      << "  --singularities <path>     Write singularities to a .sings file.\n"
      << "  --diagnostics-prefix <p>   Write field diagnostics as sidecars.\n"
      << "  --verbose                  Print processing details.\n\n"
      << "convert-field options:\n"
      << "  --input-format <auto|crossfield|neurcross|rosy|rawfield>\n"
      << "  --output-format <auto|crossfield|neurcross|rosy|rawfield>\n"
      << "  --mesh <input.obj|input.off>  Required when beta must be reconstructed from normals.\n"
      << "  --degree <2|4>                 Rawfield output degree (default 4).\n\n"
      << "compare-fields options:\n"
      << "  --first-format <auto|crossfield|neurcross|rosy|rawfield>\n"
      << "  --second-format <auto|crossfield|neurcross|rosy|rawfield>\n"
      << "  --candidate-format <...>       Alias for --first-format.\n"
      << "  --reference-format <...>       Alias for --second-format.\n"
      << "  --prefix <path-prefix>         Write CSV, PLY heatmap, and JSON sidecars.\n"
      << "  --csv <path>                   Write per-face deviation CSV.\n"
      << "  --heatmap <path>               Write per-face PLY deviation heatmap.\n"
      << "  --json <path>                  Write summary metrics JSON.\n"
      << "  --high-error-threshold <deg>   Connected-region threshold (default 20).\n"
      << "  --shape-operator-alignment     Also score each field against the proxy shape operator.\n"
      << "  --shape-no-proxy               Evaluate original mesh curvature instead of proxy curvature.\n"
      << "  --shape-proxy-fidelity <value> Shape-alignment proxy fidelity (default 1).\n"
      << "  --shape-proxy-smoothness <v>   Shape-alignment proxy smoothness (default 0.01).\n"
      << "  --shape-no-preserve-boundary   Allow shape-alignment proxy boundary movement.\n"
      << "  --shape-curvature-min-confidence <v>\n"
      << "  --shape-curvature-confidence-exponent <v>\n"
      << "  --shape-curvature-smoothing-iterations <count>\n"
      << "  --keep-global-phase            Do not remove best global 4-RoSy phase.\n\n"
      << "simplify options:\n"
      << "  --target-faces <count>       Target triangle count.\n"
      << "  --ratio <value>              Target face ratio in (0, 1] when count is omitted (default 0.5).\n"
      << "  --nvf <path>                 #V x 3 DMAT per-vertex NVF displacement t(v).\n"
      << "  --targets <path>             #V x 3 DMAT predicted target positions x(v).\n"
      << "  --root-threshold <value>     Watershed root threshold tau.\n"
      << "  --voxel-resolution <count>   Resolution used for default tau (default 512).\n"
      << "  --topology-weight <value>    Positional target quadric weight (default 0.1).\n"
      << "  --root-relaxation-threshold <value>\n"
      << "  --no-preserve-boundary       Allow boundary-to-interior collapses.\n"
      << "  --allow-face-flips           Disable local normal-flip rejection.\n"
      << "  --diagnostics-prefix <p>     Write root labels as a sidecar DMAT.\n"
      << "  --verbose                    Print simplification details.\n\n"
      << "remesh options:\n"
      << "  --field <path>                  Use crossfield, rosy, or rawfield input.\n"
      << "  --field-format <auto|crossfield|neurcross|rosy|rawfield>\n"
      << "  --field-method <smooth|regularized-curvature>\n"
      << "                                  Auto-generate this field type when no field is supplied.\n"
      << "  --raw-field <path>              Legacy degree-4 rawfield input alias.\n"
      << "  --primary-directions <path>     Legacy #F x 3 DMAT direction matrix.\n"
      << "  --secondary-directions <path>   Legacy second #F x 3 DMAT matrix.\n"
      << "  --length-ratio <value>          Target edge-length ratio (default 0.02).\n"
      << "  --no-integral-seamless          Disable integral seamless constraints.\n"
      << "  --round-seams                   Round seam values during integration.\n"
      << "  --simplification-backend <directional|triflow-dcel>\n"
      << "                                  Select generated-DCEL simplification backend.\n"
      << "  --experimental-triflow-dcel-simplify\n"
      << "                                  Alias for --simplification-backend triflow-dcel.\n"
      << "  --no-normalize-directions       Preserve supplied direction magnitudes.\n"
      << "  --proxy-fidelity <value>        Regularized proxy positional fidelity (default 1).\n"
      << "  --proxy-smoothness <value>      Regularized proxy biharmonic weight (default 0.01).\n"
      << "  --no-preserve-boundary          Allow regularized proxy boundary movement.\n"
      << "  --no-preserve-sharp-features    Allow regularized proxy feature movement.\n"
      << "  --no-feature-aware-corner-normals\n"
      << "                                  Use globally averaged normals for regularized curvature.\n"
      << "  --field-smoothness <value>      Regularized field smoothness weight.\n"
      << "  --curvature-alignment <value>   Regularized curvature alignment weight.\n"
      << "  --boundary-alignment <value>    Regularized boundary alignment weight.\n"
      << "  --sharp-feature-alignment <v>   Regularized sharp-feature alignment weight.\n"
      << "  --curvature-min-confidence <v>  Ignore weaker regularized curvature targets.\n"
      << "  --curvature-confidence-exponent <value>\n"
      << "  --curvature-smoothing-iterations <count>\n"
      << "  --curvature-sharp-angle <degrees>\n"
      << "  --smooth-curvature-across-features\n"
      << "  --diagnostics-prefix <p>        Write pipeline result arrays as sidecars.\n"
      << "  --verbose                       Print pipeline timing details.\n";
}

} // namespace directional::cli
